name: iisc project
channels:
  - conda-forge
dependencies:
  - python=3.11

  # Jupyter / docs
  - jupyterlab
  - jupyter-book
  - ghp-import
  - nbconvert
  - ipympl

  # Core scientific stack
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - h5py
  - pyarrow
  - pympler
  - tqdm

  # Particle physics / HEP
  - uproot
  - awkward
  - vector
  - hist
  - hepunits
  - particle

  # Compilers / acceleration
  - clang-tools
  - cxx-compiler
  - gfortran_linux-64=9  # <--- ADD THIS (Forces Version 9)
  - ninja
  - pybind11
  - numba
  - jax

  # Distributed computing
  - dask
  - distributed
  - dask-awkward
  - graphviz
  - python-graphviz
